### ISSUE TITLE
No matching distribution found for llmsstatemachine

### ISSUE THREAD

**Issue by abrichr** [robocorp/llm_state_machine#4]
Hello, thank you for making this great code available!

I am having trouble getting started:

```
coderip-py3.11) abrichr@MacBook-Pro-4 coderip % pip install llmsstatemachine

ERROR: Could not find a version that satisfies the requirement llmsstatemachine (from versions: none)
ERROR: No matching distribution found for llmsstatemachine
```

Do I need to clone locally? Any advice would be appreciated!

**Comment by mkorpela** [comment]
@abrichr hi,
Thanks for pointing out. I may have left too strict python version requirements.. I’ll check this soon!

**Comment by mkorpela** [comment]
@abrichr hey there is a typo in the installation command you have there.

pip install llm**S**statemachine => `pip install llmstatemachine`
